<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>footer</title>	   	

<style> 
/* CSS for footer */
footer {    
	display: flex; position: absolute; flex-shrink:0;   
	bottom: 0; margin-bottom: 0; width: 100%; clear:both; font-size: small; 
	color: #fcf; background-color: #0005; background-color: rgba(0,0,0,0.54);
  	justify-content: space-between; align-items: center; padding: 5px; 
}
</style>
	
</head>
<body>

<footer>
  
11023.. <a href="//spaceedge.com"> &copy; SpaceEdge.com </a> 
  
</footer>

</body>
</html>
